language: java
jdk:
  - oraclejdk8
  - oraclejdk9

before_install:
 - chmod +x gr
install: true

script:
  - ./gr -i build

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.gradle/wrapper/
